website_analysis_task:
  description: >
    First, scrape the publisher's website to gather content and metadata. Then analyze the content to determine:
    - Main content categories and topics
    - Target audience characteristics
    - Writing style and tone
    - Geographic focus
    Use both direct website content and search results about the publisher to build a comprehensive profile.
  expected_output: >
    A detailed analysis of the publisher's content strategy including:
    - List of main content categories
    - Target audience profile
    - Geographic coverage
    - Content style and preferences
  agent: website_analyzer

guidelines_task:
  description: "Develop and store brand voice and content guidelines using the EditorialGuidelinesTool. Consider the publisher's niche, audience, and content strategy."
  expected_output: "A comprehensive set of brand voice guidelines stored for consistent access by all agents."
  agent: content_strategist
  context: ["website_analysis_task"]

trends_research_task:
  description: >
    Research current trends and events relevant to the publisher's focus areas. Use EXASearch to:
    - Find trending topics in their main categories
    - Identify emerging industry trends
    - Discover content gaps and opportunities
  expected_output: "A list of current trends, upcoming events, and potential content gaps in the publisher's niche."
  agent: topic_researcher
  context: ["website_analysis_task", "guidelines_task"]

topic_generation_task:
  description: "Generate and score initial topic ideas ensuring alignment with audience interests and current trends. Consider the website analysis and trends research results."
  expected_output: "A list of scored topic ideas with relevance, audience appeal, and SEO potential ratings."
  agent: content_strategist
  context: ["website_analysis_task", "guidelines_task", "trends_research_task"]

diversity_check_task:
  description: "Review topic suggestions using ContentDiversityTool to ensure diversity in content types and subject matter. Check for duplicates and overlapping themes."
  expected_output: "A validated list of topics ensuring diversity in content types and subject matter."
  agent: quality_assurer
  context: ["topic_generation_task"]

final_compilation_task:
  description: "Compile the final list of topic suggestions ensuring alignment with guidelines and incorporating diversity check results. Prioritize topics based on relevance and potential impact."
  expected_output: "A prioritized list of topic suggestions ready for implementation."
  agent: topic_coordinator
  context: ["website_analysis_task", "guidelines_task", "diversity_check_task"]
