research_topics:
  description: Research and identify trending topics in the specified domain
  expected_output: A list of potential topics with descriptions and keywords

analyze_topics:
  description: Analyze topics for audience fit and potential impact
  expected_output: Analyzed topics with audience fit scores and recommendations

write_content:
  description: Create high-quality content for the selected topic
  expected_output: Complete article or content piece following guidelines

edit_content:
  description: Review and edit content for quality and consistency
  expected_output: Edited content with improvements and suggestions

write_pitch:
  description: Create a compelling pitch for the content
  expected_output: Complete pitch with headline, body, and key points

optimize_pitch:
  description: Optimize the pitch for specific publishers
  expected_output: Optimized pitch with publisher-specific adjustments