research_task:
  description: "Research the topic: {topic}
    1. Identify key themes and insights
    2. Gather supporting data and examples
    3. Validate information from multiple sources
    4. Compile findings in a structured format."
  expected_output: "A comprehensive research package including main themes and insights, supporting data points, credible sources used, and potential angles for content development."
  agent: content_researcher

content_writing_task:
  description: "Write engaging content based on the research package and editorial guidelines. Structure content for readability and impact while maintaining the required tone and style."
  expected_output: "A well-structured draft that incorporates research findings and follows editorial guidelines."
  agent: content_writer
  context:
    - research_task

editing_task:
  description: "Review and edit the content for clarity, accuracy, and style. Ensure compliance with editorial guidelines and brand standards. Check grammar, tone, and flow."
  expected_output: "An edited version of the content with tracked changes and editorial comments."
  agent: content_editor
  context:
    - content_writing_task

optimization_task:
  description: "Optimize the content for search engines and reader engagement. Analyze readability, keyword usage, and structure. Suggest improvements for better performance."
  expected_output: "An optimized version of the content with SEO improvements and engagement enhancements."
  agent: content_optimizer
  context:
    - editing_task

final_review_task:
  description: "Conduct final review of the optimized content. Ensure all elements are in place and the content is ready for publication. Prepare content package with metadata."
  expected_output: "Publication-ready content package with all necessary metadata and supporting materials."
  agent: content_coordinator
  context:
    - optimization_task
