content_research:
  description: "Conduct thorough research on the topic at hand, focusing on identifying and analyzing key themes and insights that emerge from the literature. Gather robust supporting data and relevant examples to strengthen your findings. Additionally, ensure the accuracy and reliability of the information by cross-referencing and validating it with multiple credible sources. This comprehensive approach will help create a well-rounded understanding of the subject."
  expected_output: "A detailed research package that includes main themes and insights, relevant data points, credible sources, and potential content development angles."
  agent: content_researcher

content_writing_task:
  description: "Write engaging content based on the research package and editorial guidelines. Structure content for readability and impact while maintaining the required tone and style."
  expected_output: "A well-structured draft that incorporates research findings and follows editorial guidelines."
  agent: content_writer
  context: ["content_research"]

editing_task:
  description: "Review and edit the content for clarity, accuracy, and style. Ensure compliance with editorial guidelines and brand standards. Check grammar, tone, and flow."
  expected_output: "An edited version of the content with tracked changes and editorial comments."
  agent: content_editor
  context: ["content_writing_task"]

optimization_task:
  description: "Optimize the content for search engines and reader engagement. Analyze readability, keyword usage, and structure. Suggest improvements for better performance."
  expected_output: "An optimized version of the content with SEO improvements and engagement enhancements."
  agent: content_optimizer
  context: ["editing_task"]

content_review:
  description: "Conduct final review of the optimized content. Ensure all elements are in place and the content is ready for publication. Prepare content package with metadata."
  expected_output: "Publication-ready content package with all necessary metadata and supporting materials."
  agent: content_coordinator
  context: ["optimization_task"]
