brand_analysis_task:
  description: "Analyze the brand's fit with available topics and publishers using the BrandMatchingTool. Consider brand values, target market, and unique selling propositions."
  expected_output: "A prioritized list of brand-topic-publisher matches with detailed rationale for each match."
  agent: brand_analyst

pitch_writing_task:
  description: "Create compelling PR pitches for the high-priority matches using PitchGeneratorTool. Ensure each pitch highlights the unique value proposition and aligns with the topic."
  expected_output: "A set of initial PR pitches with subject lines, body content, and calls to action."
  agent: pitch_writer
  context:
    - brand_analysis_task

pitch_optimization_task:
  description: "Optimize each pitch using PitchOptimizationTool based on publisher preferences and historical data. Refine language, structure, and timing for maximum impact."
  expected_output: "A set of optimized pitches with publisher-specific adjustments and timing recommendations."
  agent: media_relations_specialist
  context:
    - pitch_writing_task

final_review_task:
  description: "Review and finalize all pitches ensuring quality, consistency, and strategic alignment. Prepare delivery schedule and tracking system."
  expected_output: "Final pitch package with delivery schedule and success metrics tracking plan."
  agent: pitch_coordinator
  context:
    - pitch_optimization_task
